spring.application.name=message-service
server.port=8084

# SQLite Configuration
spring.datasource.url=jdbc:sqlite:message_service.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging configuration
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
logging.level.com.example.messageservice=DEBUG

management.endpoints.web.cors.allowed-origins=*
management.endpoints.web.cors.allowed-methods=*
management.endpoints.web.cors.allowed-headers=*

# Disable CSRF for development
spring.security.enabled=false


# Service URLs
service.user-service.url=http://localhost:8080

# JWT Configuration
app.jwt.secret=dogparklmao
app.jwt.expiration=900000